---
- name: Common setup
  hosts: allnodes
  gather_facts: True
  user: pi
  become: True
  tags: common

  roles:
    - aptcache
    - common_packages
    - mpi_packages
    - nfs_common


- name: Master setup
  hosts: master
  user: pi
  become: True
  tags: master

  roles:
    - { role: create_cluster_user, generate_master_key: "yes" }
    - { role: ssh_keys, ssh_user: cluster, public_key_directory: publickeys }
    - nfs_master
    - mpi_config

- name: Slave setup
  hosts: slaves
  gather_facts: True
  user: pi
  become: True
  tags: slave

  roles:
    - { role: create_cluster_user, generate_master_key: "no" }
    - { role: ssh_keys, ssh_user: cluster, public_key_directory: publickeys }
    - { role: ssh_keys, ssh_user: cluster, public_key_directory: fetchedkeys }
    - nfs_slaves

- name: All nodes start service
  hosts: allnodes
  user: pi
  become: True
  tags: common

  roles:
    - nfs_common_startup



