---
- name: Common setup
  hosts: allnodes
  gather_facts: True
  user: pi
  become: True
  tags: common

  roles:
    - aptcache
    - mpi_common
    - nfs_common


- name: Master setup
  hosts: master
  user: pi
  become: True
  tags: master

  roles:
    - { role: create_cluster_user, generate_master_key: "yes" }
    - { role: ssh_keys, ssh_user: cluster, public_key_directory: publickeys }
    - nfs_master
    - mpi_config

- name: Slave
  hosts: slaves
  gather_facts: True
  user: pi
  become: True
  tags: slave

  roles:
    - { role: create_cluster_user, generate_master_key: "no" }
    - { role: ssh_keys, ssh_user: cluster, public_key_directory: publickeys }
    - { role: ssh_keys, ssh_user: cluster, public_key_directory: fetchedkeys }
    - nfs_slaves




