---
- name: Common setup
  hosts: allnodes
  gather_facts: True
  user: pi
  become: True
  tags: common

  roles:
    - mpi_common
    - nfs_common


- name: Master setup
  hosts: master
  user: pi
  become: True
  tags: master

  roles:
    - { role: create_cluster_user, generate_master_key: "yes" }
    - nfs_master

- name: Slave
  hosts: slavenodes
  gather_facts: True
  user: pi
  become: True
  tags: slave

  roles:
    - nfs_slaves




