---
- name: Prerequisites
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Check password is set
      fail:
      when: pi_password is not defined
      tags: always


- name: Common setup before keys
  hosts: "{{ init_hosts | default('allnodes')}}"
  gather_facts: yes
  user: pi
  become: yes
  tags: initialise

  roles:

    - raspconfig
    - { role: ssh_keys, ssh_user: root }
    - { role: ssh_keys, ssh_user: pi }
    - { role: set_pi_password, user_password: "{{ pi_password }}", tags: reset_password }

- name: Common setup after keys added
  hosts: "{{ init_hosts | default('allnodes')}}"
  gather_facts: no
  user: pi
  become: yes
  tags: initialise

  pre_tasks:

    - name: Ensure that the password for SSH connections is now as above
      set_fact:
        ansible_ssh_pass: "{{ pi_password }}"

  roles:
    - reboot

- name: Wait for the hosts to be available
  hosts: "{{ init_hosts | default('allnodes')}}"
  gather_facts: no
  become: no

  roles:
    - wait_for_ssh
