---
- name: Setup public keys
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup( 'file', item ) }}"
  with_fileglob:
        - "{{ public_key_base }}{{ public_key_directory }}{{ public_key_files }}"
