---
- name: Copy master vol.autofs to config
  copy:
    src: etc-files/auto.master.d/vol.autofs-master
    dest: /etc/auto.master.d/vol.autofs
    mode: 0744

- name: Copy master auto.vol to config
  copy:
    src: etc-files/auto.vol-master
    dest: /etc/auto.vol
    mode: 0744

- name: Copy master exports file
  copy:
    src: etc-files/exports-master
    dest: /etc/exports
    mode: 0744
