---
- name: Make the /vol directory
  file:
    path: /vol
    mode: 0777
    state: directory

- name: Copy master vol.autofs to config
  copy:
    src: vol.autofs-master
    dest: /etc/auto.master.d/vol.autofs
    mode: 0744

- name: Copy master auto.vol to config
  copy:
    src: auto.vol-master
    dest: /etc/auto.vol
    mode: 0744

- name: Copy master exports file
  copy:
    src: exports-master
    dest: /etc/exports
    mode: 0744
